// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderTrackingApi.Data;

#nullable disable

namespace OrderTrackingApi.Migrations
{
    [DbContext(typeof(TrackingDbContext))]
    [Migration("20250326222058_EditTrackingRequest")]
    partial class EditTrackingRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("OrderTrackingApi.Models.TrackingModel", b =>
                {
                    b.Property<string>("OrderNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingNumbers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OrderNumber");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
